# Generated by Django 4.0.6 on 2022-07-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_pizzeria_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pizzeria',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.TextField(max_length=50),
        ),
    ]
