# Generated by Django 4.0.6 on 2022-07-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_alter_entry_text_alter_pizzeria_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
