# Generated by Django 4.0.6 on 2022-07-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_alter_pizzeria_name_alter_topping_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topping',
            new_name='Pizza',
        ),
    ]
