# Generated by Django 4.0.6 on 2022-07-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_pizzeria_owner_topic_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
